# El nombre de tu proyecto
spring.application.name=veterinaria

# LA URL: Apuntamos a la base "veterinaria" que acabás de crear
spring.datasource.url=jdbc:mysql://localhost:3306/veterinaria?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- LA MAGIA DE JPA ---
# "update" hace que Spring lea tus clases @Entity y cree las tablas en MySQL por vos automáticamente.
spring.jpa.hibernate.ddl-auto=update

# Para ver en la consola el código SQL que Spring genera por detrás
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
