spring.application.name=Guia3JPA

# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/banco?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin

# Le decimos a Hibernate (el motor de JPA) que actualice las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

